# Metrics Server values for production environments (AWS EKS, etc.)
# This configuration uses secure TLS for kubelet communication

defaultArgs:
  - --cert-dir=/tmp
  - --secure-port=4443
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --kubelet-use-node-status-port
  - --metric-resolution=15s
  # No --kubelet-insecure-tls for production security

containerPort: 4443
securePort: 4443

# Production resource limits
resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 500m
    memory: 500Mi

# High availability settings
replicas: 2

# Pod disruption budget for production
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Anti-affinity to spread pods across nodes
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - metrics-server
        topologyKey: kubernetes.io/hostname

# Node selector for production workloads (optional)
# nodeSelector:
#   node-type: system