# Kind-specific values for local testing
# This overrides the main values.yaml for kind deployment

# Use default storage class for kind
wordpress:
  persistence:
    storageClass: "standard" # kind's default storage class
    size: 5Gi # Smaller for local testing
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "50m"
      memory: "200Mi"
  # livenessProbe:
  #   enabled: false
  # readinessProbe:
  #   enabled: false

additionalLabels:
  environment: demo
  team: platform
  app: wordpress
  version: "1.0"

mysql:
  image:
    repository: mariadb
    tag: "10.11"
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    storageClass: "standard" # kind's default storage class
    accessModes:
      - ReadWriteOnce
    size: 5Gi # Smaller for local testing
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "512Mi"

# Use NodePort for easier local access
service:
  type: NodePort
  port: 80

# Single replica for testing
replicaCount: 1

# HPA configuration for demo
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 60

# Reduce resource quotas for kind
resourceQuota:
  requests:
    cpu: "4"
    memory: 4Gi
  limits:
    cpu: "8"
    memory: 8Gi
  persistentvolumeclaims: "5"
  pods: "20"
