# Default values for wordpress.
# This is a YAML-formatted file.

# Namespace configuration
namespace: wordpress-demo

# Global configuration
nameOverride: ""
fullnameOverride: ""

# Use existing secret (set to false to create new secret)
existingSecret: ""

# WordPress configuration
wordpress:
  image:
    repository: wordpress
    tag: "6.4.2-apache"
    pullPolicy: IfNotPresent

  # WordPress admin configuration
  username: admin
  password: "" # Set via --set-string or external secret
  email: admin@example.com
  firstName: Admin
  lastName: User
  blogName: "Custom WordPress Demo"

  # Resource configuration
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

  # Persistence configuration
  persistence:
    enabled: true
    storageClass: "gp3-encrypted"
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  # Health checks
  livenessProbe:
    enabled: true
    path: /wp-admin/install.php
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

  readinessProbe:
    enabled: true
    path: /wp-admin/install.php
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

# MySQL configuration
mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent

  # Database configuration
  database: wordpress
  user: wordpress
  password: "" # Set via --set-string or external secret
  rootPassword: "" # Set via --set-string or external secret

  # Resource configuration
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

  # Persistence configuration
  persistence:
    enabled: true
    storageClass: "gp3-encrypted"
    accessModes:
      - ReadWriteOnce
    size: 20Gi

# Service configuration
service:
  type: LoadBalancer
  port: 80
  httpsPort: 443
  annotations: {}

# Replica configuration
replicaCount: 2

# Security configuration
security:
  podSecurityStandard:
    enforce: baseline
    audit: restricted
    warn: restricted

# Resource quota configuration
resourceQuota:
  requests:
    cpu: "4"
    memory: 8Gi
  limits:
    cpu: "8"
    memory: 16Gi
  persistentvolumeclaims: "10"
  pods: "20"

# Limit range configuration
limitRange:
  default:
    cpu: "500m"
    memory: "512Mi"
  defaultRequest:
    cpu: "100m"
    memory: "128Mi"

# Autoscaling configuration (HPA)
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
