apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-mysql
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress.mysql.labels" . | nindent 4 }}
spec:
  ports:
  - port: 3306
    targetPort: mysql
    protocol: TCP
    name: mysql
  selector:
    {{- include "wordpress.mysql.selectorLabels" . | nindent 4 }}
  type: ClusterIP