apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.fullname" . }}-mysql-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress.mysql.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.mysql.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size | quote }}
  {{- if .Values.mysql.persistence.storageClass }}
  storageClassName: {{ .Values.mysql.persistence.storageClass | quote }}
  {{- end }}