apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    app.kubernetes.io/name: {{ include "wordpress.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    # Pod Security Standards
    pod-security.kubernetes.io/enforce: {{ .Values.security.podSecurityStandard.enforce }}
    pod-security.kubernetes.io/audit: {{ .Values.security.podSecurityStandard.audit }}
    pod-security.kubernetes.io/warn: {{ .Values.security.podSecurityStandard.warn }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "wordpress.fullname" . }}-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.requests.cpu | quote }}
    requests.memory: {{ .Values.resourceQuota.requests.memory }}
    limits.cpu: {{ .Values.resourceQuota.limits.cpu | quote }}
    limits.memory: {{ .Values.resourceQuota.limits.memory }}
    persistentvolumeclaims: {{ .Values.resourceQuota.persistentvolumeclaims | quote }}
    pods: {{ .Values.resourceQuota.pods | quote }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "wordpress.fullname" . }}-limits
  namespace: {{ .Values.namespace }}
spec:
  limits:
    - default:
        cpu: {{ .Values.limitRange.default.cpu | quote }}
        memory: {{ .Values.limitRange.default.memory }}
      defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequest.cpu | quote }}
        memory: {{ .Values.limitRange.defaultRequest.memory }}
      type: Container