{{- if not .Values.existingSecret }}
{{- $wordpressPassword := .Values.wordpress.password | default (randAlphaNum 16) }}
{{- $mysqlPassword := .Values.mysql.password | default (randAlphaNum 16) }}
{{- $mysqlRootPassword := .Values.mysql.rootPassword | default (randAlphaNum 16) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  wordpress-password: {{ $wordpressPassword | b64enc | quote }}
  mysql-root-password: {{ $mysqlRootPassword | b64enc | quote }}
  mysql-password: {{ $mysqlPassword | b64enc | quote }}
{{- end }}