# AWS Load Balancer Controller Helm values
# Replace the placeholder values with your actual cluster information

# Cluster configuration - REPLACE THESE VALUES
clusterName: "jamf-demo-cluster"
region: "us-east-2"
vpcId: "vpc-04e8e7fb327fa8b30"

# Service Account configuration
serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::186582696199:role/AmazonEKSLoadBalancerControllerRole"

# Resource configuration
resources:
  limits:
    cpu: 200m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 200Mi

# High availability
replicaCount: 2

# Pod disruption budget
podDisruptionBudget:
  maxUnavailable: 1

# Node selector for system workloads (optional)
# nodeSelector:
#   node-type: system

# Tolerations for dedicated nodes (optional)
# tolerations:
#   - key: "node-type"
#     operator: "Equal"
#     value: "system"
#     effect: "NoSchedule"

# Anti-affinity to spread replicas across nodes
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - aws-load-balancer-controller
        topologyKey: kubernetes.io/hostname

# Security context
securityContext:
  fsGroup: 65534